---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: manager-role
rules:
- apiGroups:
  - ""
  resources:
  - secrets
  - services
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - triggers.harikube.info
  resources:
  - httptriggers
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - triggers.harikube.info
  resources:
  - httptriggers/finalizers
  verbs:
  - update
- apiGroups:
  - triggers.harikube.info
  resources:
  - httptriggers/status
  verbs:
  - get
  - patch
  - update
