---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: manager-role
rules:
- apiGroups:
  - triggers.harikube.info
  resources:
  - openfaastriggers
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - triggers.harikube.info
  resources:
  - openfaastriggers/finalizers
  verbs:
  - update
- apiGroups:
  - triggers.harikube.info
  resources:
  - openfaastriggers/status
  verbs:
  - get
  - patch
  - update
