## Append samples of your project ##
resources:
- triggers_v1_minimal.yaml
- triggers_v1_full.yaml
- triggers_v1_ai_minimal.yaml
- triggers_v1_ai_full.yaml
# +kubebuilder:scaffold:manifestskustomizesamples
