apiVersion: triggers.harikube.info/v1
kind: HTTPTrigger
metadata:
  name: minimal-httptrigger-example
  namespace: default
spec:
  resource:
    apiVersion: apps/v1
    kind: Deployment
  url:
    static: "https://example.com/hook"
    # template: "https://example.com/hook/{{ .metadata.name }}"
    # service:
    #   name: kubernetes
    #   namespace: default
    #   scheme: https
    #   uri:
    #     template: "/hook/{{ .metadata.name }}"
  method: GET
