apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - node-notready-self-heal.yaml
  - deployment-zero-available-replicas.yaml
  - pvc-pending-storage-investigator.yaml
  - job-failure-responder.yaml
  - email-sensitive-data-review.yaml
  - transaction-validation-wakeup.yaml
  - federation-booking-acceptance.yaml
