name: Release

on:
  push:
    branches:
    - release-v**
    - rc-v**
    - beta-v**
    - alpha-v**
    - dev-v**

concurrency: 
  group: ${{ github.ref_name }}-release
  cancel-in-progress: true

permissions:
  contents: write

env:
  GITHUB_TOKEN: ${{ secrets.GIT_TOKEN  }}
  
jobs:
  release:
    runs-on: ubuntu-latest
    timeout-minutes: 10
    steps:
    - name: Clone the code
      uses: actions/checkout@v4
      with:
          fetch-depth: 0
    - name: Setup Go
      uses: actions/setup-go@v5
      with:
          go-version-file: go.mod
    - name: Extract branch name
      run: echo "branch=${GITHUB_HEAD_REF:-${GITHUB_REF#refs/heads/}}" >> $GITHUB_OUTPUT
      id: extract_branch
    - name: Build image
      run: make docker-build
      env:
        IMG: ${{ vars.REGISTRY }}/${{ vars.REGISTRY_USER }}/serverless-kube-watch-trigger:${{ steps.extract_branch.outputs.branch }}
    - name: Login to registry
      uses: docker/login-action@v3
      with:
        registry: ${{ vars.REGISTRY }}
        username: ${{ vars.REGISTRY_USER }}
        password: ${{ secrets.REGISTRY_TOKEN }}
    - name: Push image
      run: make docker-push
      env:
        IMG: ${{ vars.REGISTRY }}/${{ vars.REGISTRY_USER }}/serverless-kube-watch-trigger:${{ steps.extract_branch.outputs.branch }}
    - name: Generate bundle
      run: make package
      env:
        IMG: ${{ vars.REGISTRY }}/${{ vars.REGISTRY_USER }}/serverless-kube-watch-trigger:${{ steps.extract_branch.outputs.branch }}
    - name: Create release
      if: ${{ !startsWith(github.ref, 'refs/heads/dev-') }}
      uses: mhmxs/milestone-release-action@main
      with:
        milestone-title: ${{ steps.extract_branch.outputs.branch }}
        pre-body: |
            # serverless-kube-watch-trigger
            A lightweight Kubernetes operator that turns **Kubernetes API server watch events into trigger sources** for serverless functions and external systems. It allows you to declaratively define *when* and *how* functions or webhooks should fire in response to changes in Kubernetes resources — without modifying the API server or deploying heavy eventing frameworks.

            ## Configuration
            For apply any configuration option please edit the Kubernetes manifests below and add extra arguments there.

            - `--namespace`: The namespace the operator reacts on trigger events. Default is all namespaces.
            - `--label-selectors`: The label selectors the operator reacts on trigger events.
            - `--field-selectors`: The field selectors the operator reacts on trigger events.

            ## Installation
            `kubectl apply -f https://github.com/HariKube/serverless-kube-watch-trigger/releases/download/${{ steps.extract_branch.outputs.branch }}/bundle.yaml`

            ## Release Notes
        draft: true
        prerelease: ${{ startsWith(github.ref, 'refs/heads/rc-') || startsWith(github.ref, 'refs/heads/beta-') || startsWith(github.ref, 'refs/heads/alpha-') }}
        files: package/bundle.yaml
  
